version: "3.5"
services:
  db:
    container_name: db
    image: mysql/mysql-server:latest-aarch64
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'allico'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'irtic'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'irtic'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./db:/var/lib/mysql
  backend:
    container_name: backend
    image: maven:3-openjdk-17
    ports:
      - "8080:8080"
    volumes:
      - ./book:/usr/src/mymaven
    command:  /bin/bash -c "tail -f /dev/null"